EntityFrameworkMvc/EntityFrameworkMvc/Controllers/AuthorController.cs
using EntityFrameworkMvc.Data;
using EntityFrameworkMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkMvc.Controllers
{
    public class AuthorController : Controller
    {
        private readonly AppDbContext _context;

        public AuthorController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var authors =  await _context.Authors.ToListAsync();

            return View(authors);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Author author)
        {
            if(ModelState.IsValid)
            {
                _context.Authors.Add(author);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var authors = await _context.Authors.FindAsync(id);

            if(authors != null)
            {
                return View(authors);
            }
            else
            {
                return RedirectToAction("Index");   
            }
        }


        [HttpPost]
        public async Task<IActionResult> Update(int AuthorId,Author author)
        {
            var isThereAnyAuthor = _context.Authors.Find(AuthorId);

            if(isThereAnyAuthor != null)
            {
                isThereAnyAuthor.AuthorName = author.AuthorName;
                isThereAnyAuthor.AuthorBirthDate = author.AuthorBirthDate;
                isThereAnyAuthor.AuthorsBirthPlace = author.AuthorsBirthPlace;
                isThereAnyAuthor.AuthorsSchool = author.AuthorsSchool;

                _context.Authors.Update(isThereAnyAuthor);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var deleteAuthor = await _context.Authors.FindAsync(id);

            if(deleteAuthor != null)
            {
                 _context.Authors.Remove(deleteAuthor);
                 await _context.SaveChangesAsync();

                return Json(new {message = "Author deleted sucessfully"});
            }
            else
            {
                return RedirectToAction("Index");
            }
        }



    }
}

EntityFrameworkMvc/EntityFrameworkMvc/Controllers/BookController.cs
using EntityFrameworkMvc.Data;
using EntityFrameworkMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkMvc.Controllers
{
    public class BookController : Controller
    {
        private readonly AppDbContext _context;

        public BookController(AppDbContext appDbContext)
        {
            _context = appDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await _context.Books.Include(x => x.Author).ToListAsync();

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var result = await _context.Authors.ToListAsync();

            ViewBag.Authors = result;

            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(Book book)
        {
            if(ModelState.IsValid)
            {
                await _context.Books.AddAsync(book);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Update(int id)
        {
            var result = await _context.Authors.ToListAsync();

            ViewBag.Authors = result;

            var currentBook = await _context.Books.FindAsync(id);

            if(currentBook != null) 
            {
                return View(currentBook);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task <ActionResult> Update(int BookId,Book book)
        {
            var isThereAnyBook = await _context.Books.FindAsync(BookId);

            if(isThereAnyBook != null)
            {
                isThereAnyBook.BookName = book.BookName;
                isThereAnyBook.BookDescription = book.BookDescription;
                isThereAnyBook.BookYearOfPublication = book.BookYearOfPublication;
                isThereAnyBook.AuthorId = book.AuthorId;

                _context.Update(isThereAnyBook);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var book = await _context.Books.FindAsync(id);

            if(book != null)
            {
                _context.Remove(book);
                await _context.SaveChangesAsync();

                return Json(new { message = "Book deleted successfully" });
            }
            else
            {
                return NotFound();
            }
        }

       

    }
}

EntityFrameworkMvc/EntityFrameworkMvc/Controllers/PublisherController.cs
using EntityFrameworkMvc.Data;
using EntityFrameworkMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkMvc.Controllers
{
    public class PublisherController : Controller
    {
        private readonly AppDbContext _context;

        public PublisherController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var publishers = await _context.Publishers.ToListAsync();

            return View(publishers);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Publisher p)
        {
            if (ModelState.IsValid)
            {
                _context.Publishers.Add(p);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var publishers = await _context.Publishers.FindAsync(id);

            if (publishers != null)
            {
                return View(publishers);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        public async Task<IActionResult> Update(int PublisherId, Publisher x)
        {
            var isThereAnyPublisher = _context.Publishers.Find(PublisherId);

            if (isThereAnyPublisher != null)
            {
                isThereAnyPublisher.PublisherName = x.PublisherName;
           

                _context.Publishers.Update(isThereAnyPublisher);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var deletePublisher = await _context.Publishers.FindAsync(id);

            if (deletePublisher != null)
            {
                _context.Publishers.Remove(deletePublisher);
                await _context.SaveChangesAsync();

                return Json(new { message = "Publisher deleted sucessfully" });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


    }
}

EntityFrameworkMvc/EntityFrameworkMvc/Controllers/RegisterController.cs
using EntityFrameworkMvc.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EntityFrameworkMvc.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public RegisterController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Register(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Name, Password = model.Password,Role = model.Role }; 

                var result = await _userManager.CreateAsync(user, model.Password); 

                if (result.Succeeded)
                {
                    if(model.Role == null)
                    {
                        return BadRequest("Invalid role");
                    }
                    else if (model.Role == "Admin" || model.Role == "User")
                    {
                        await _userManager.AddToRoleAsync(user, model.Role);

                        return View();
                    }
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

    }
}

EntityFrameworkMvc/EntityFrameworkMvc/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="" />
    <meta name="description" content="" />
    <meta name="keywords" content="bulma, login, page, website, template, free, awesome" />
    <link rel="canonical" href="https://aldi.github.io/bulma-login-template/" />
    <title>Library Management Login Page</title>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css" />
    <link rel="stylesheet" href="css/styles.css" />
</head>
<body>
    @RenderBody()
</body>
</html>

<style>
    html,
    body {
        font-family: 'Quicksand', serif;
        font-size: 14px;
        font-weight: 300;
    }

    html {
        overflow-y: hidden !important;
        background-image: url('../media/background.jpg') !important;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }

    .hero.is-success {
        background: #f2f6fa;
    }

        .hero .nav,
        .hero.is-success .nav {
            -webkit-box-shadow: none;
            box-shadow: none;
        }

    .box {
        margin-top: 5rem;
        background-color: rgba(255, 255, 255, 0.1);
    }

    input {
        font-weight: 300;
    }

    p {
        font-weight: 700;
    }

        p.subtitle {
            padding-top: 1rem;
        }

    a {
        color: #fff;
    }

        a:hover {
            color: #bababa;
        }

    .languages {
        margin-top: 10px;
    }

    .footer-text {
        font-weight: initial;
    }
</style>

EntityFrameworkMvc/EntityFrameworkMvc/Views/Shared/_Layout.cshtml
@using EntityFrameworkMvc.Models
@using System.Text.Json;
@{
    var userModelJson = Context.Session.GetString("UserModel");
    var userModel = JsonSerializer.Deserialize<ApplicationUser>(userModelJson);
    var userRole = userModel?.Role;
    var userName = userModel?.UserName;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EntityFrameworkMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Shop Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <p>Name: @userName</p>
                <p>Role: @userRole</p>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (userRole == "Admin" || userRole == "User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">list authors and create author profiles</a>
                            </li>
                        }
                        @if (userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Create">create author</a>
                            </li>
                        }
                        @if (userRole == "Admin" || userRole == "User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AuthorProfile" asp-action="Index">view author profile</a>
                            </li>
                        }
                        @if (userRole == "Admin" || userRole == "User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">list books and the author of the book</a>
                            </li>
                        }
                        @if (userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Create">create book by author</a>
                            </li>
                        }
                        @if (userRole == "Admin" || userRole == "User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">publishing house list</a>
                            </li>
                        }
                        @if (userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Create">create a publishing house</a>
                            </li>
                        }
                        @if (userRole == "Admin" || userRole == "User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AuthorPublisher" asp-action="Index">view publishing houses where the author works</a>
                            </li>
                        }
                        @if (userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AuthorPublisher" asp-action="Create">add publishing houses where the author's works</a>
                            </li>
                        }
                        @if (userRole == "Admin" || userRole == "User")
                        {
                            <li class="btn btn-danger">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Information" asp-action="Search">search writer</a>
                            </li>
                        }
                        @if (userRole == "Admin")
                        {
                            <li class="btn btn-danger">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EntityFrameworkMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>