EntityFrameworkMvc/EntityFrameworkMvc/Models/Author.cs
namespace EntityFrameworkMvc.Models
{
    public class Author
    {
        public int AuthorId { get; set; }

        public string? AuthorName { get; set; }

        public DateTime? AuthorBirthDate { get; set; }

        public string? AuthorsBirthPlace { get; set; }

        public string? AuthorsSchool { get; set; }

        public List<Book> ?Books { get; set; }

        public AuthorProfile? AuthorProfile { get; set; }

        public List<AuthorPublisher> ?AuthorPublishers { get; set; }
    }
}

EntityFrameworkMvc/EntityFrameworkMvc/Controllers/AuthorController.cs
using EntityFrameworkMvc.Data;
using EntityFrameworkMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkMvc.Controllers
{
    public class AuthorController : Controller
    {
        private readonly AppDbContext _context;

        public AuthorController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var authors =  await _context.Authors.ToListAsync();

            return View(authors);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Author author)
        {
            if(ModelState.IsValid)
            {
                _context.Authors.Add(author);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var authors = await _context.Authors.FindAsync(id);

            if(authors != null)
            {
                return View(authors);
            }
            else
            {
                return RedirectToAction("Index");   
            }
        }


        [HttpPost]
        public async Task<IActionResult> Update(int AuthorId,Author author)
        {
            var isThereAnyAuthor = _context.Authors.Find(AuthorId);

            if(isThereAnyAuthor != null)
            {
                isThereAnyAuthor.AuthorName = author.AuthorName;
                isThereAnyAuthor.AuthorBirthDate = author.AuthorBirthDate;
                isThereAnyAuthor.AuthorsBirthPlace = author.AuthorsBirthPlace;
                isThereAnyAuthor.AuthorsSchool = author.AuthorsSchool;

                _context.Authors.Update(isThereAnyAuthor);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var deleteAuthor = await _context.Authors.FindAsync(id);

            if(deleteAuthor != null)
            {
                 _context.Authors.Remove(deleteAuthor);
                 await _context.SaveChangesAsync();

                return Json(new {message = "Author deleted sucessfully"});
            }
            else
            {
                return RedirectToAction("Index");
            }
        }



    }
}

EntityFrameworkMvc/EntityFrameworkMvc/Controllers/AuthorProfileController.cs
using EntityFrameworkMvc.Data;
using EntityFrameworkMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkMvc.Controllers
{
    public class AuthorProfileController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public AuthorProfileController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await _appDbContext.AuthorProfiles.Include(x=>x.Author).ToListAsync();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
           if(id == 0)
            {
                return NotFound("There is no id for author");
            }
            else
            {
                AuthorProfile authorProfile = new AuthorProfile();  
                authorProfile.AuthorId = id;
                return View(authorProfile);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorProfile authorProfile)
        {
            if (ModelState.IsValid)
            {
                await _appDbContext.AuthorProfiles.AddAsync(authorProfile);
                await _appDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var result = await _appDbContext.AuthorProfiles.FindAsync(id);

            if(result != null)
            {
                return View(result);
            }
            else
            {
                return RedirectToAction("Index");   
            }
        }


        [HttpPost]
        public async Task<IActionResult> Update(int AuthorProfileId,AuthorProfile authorProfile)
        {
            var result = await _appDbContext.AuthorProfiles.FindAsync(AuthorProfileId);
            
            if(result != null)
            {
                result.SocialMedia = authorProfile.SocialMedia;
                result.WebSite = authorProfile.WebSite;
               
                _appDbContext.Update(result);
                await _appDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
          
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var result = await _appDbContext.AuthorProfiles.FindAsync(id);

            if (result != null)
            {
                _appDbContext.Remove(result);
                await _appDbContext.SaveChangesAsync();

                return Json(new { message = "AuthorProfile deleted successfully" });
            }
            else
            {
                return NotFound();
            }
        }

    }
}

EntityFrameworkMvc/EntityFrameworkMvc/Views/Author/Create.cshtml
@model EntityFrameworkMvc.Models.Author

@{

}

<form method="post" action="Create">
    <div>
        <h3>Create Author</h3>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author Name</label>
        <input asp-for="AuthorName" type="text" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author Birth Date</label>
        <input asp-for="AuthorBirthDate" type="datetime-local" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorBirthDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author Birth Place</label>
        <input asp-for="AuthorsBirthPlace" type="text" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorsBirthPlace" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author's School</label>
        <input asp-for="AuthorsSchool" type="text" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorsSchool" class="text-danger"></span>
    </div>
    

    <button type="submit" class="btn btn-primary mt-3">Add Author</button>
</form>

EntityFrameworkMvc/EntityFrameworkMvc/Views/Author/Index.cshtml
@model List<EntityFrameworkMvc.Models.Author>

@{

}

<script src="~/js/site.js"></script>

<form id="authorIndexForm">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold">Author List</h6>
        </div>
        <div class="card-body">
            <div class="row">
            </div>
            <div id="table-scroll" class="table-responsive">
                <table id="veriTable" class="table table rounded" width="100%" cellspacing="0">
                    <thead class="table-dark">
                        <tr>
                            <th>Author ID</th>
                            <th>Author Name</th>
                            <th>Author Birth Date</th>
                            <th>Author Birth Place</th>
                            <th>Author's School</th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(Model != null)
                        {
                            foreach(var item in Model)
                            {
                                <tr>
                                    <td>@item.AuthorId</td>
                                    <td>@item.AuthorName</td>
                                    <td>@item.AuthorBirthDate</td>
                                    <td>@item.AuthorsBirthPlace</td>
                                    <td>@item.AuthorsSchool</td>
                                    <td>
                                        <button type="submit" class="btn btn-primary" asp-action="Update" asp-controller="Author" asp-route-id="@item.AuthorId">Update Author</button>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-danger" asp-action="Delete" asp-controller="Author" onclick="deleteAuthorFunction('@item.AuthorId')">Delete Author</button>
                                    </td>
                                    <td class="btn btn-secondary">
                                        <a href='@Url.Action("Create","AuthorProfile",new {id = item.AuthorId})')'>
                                            Create Author Profile By Author
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>

EntityFrameworkMvc/EntityFrameworkMvc/Views/Author/Update.cshtml
@model EntityFrameworkMvc.Models.Author

@{

}

<form method="post" action="Update">
    <input type="hidden" asp-for="AuthorId" />
    <div>
        <h3>Update Author</h3>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author Name</label>
        <input asp-for="AuthorName" type="text" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author Birth Date</label>
        <input asp-for="AuthorBirthDate" type="datetime-local" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorBirthDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author Birth Place</label>
        <input asp-for="AuthorsBirthPlace" type="text" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorsBirthPlace" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Author's School</label>
        <input asp-for="AuthorsSchool" type="text" class="form-control" id="exampleFormControlInput1">
        <span asp-validation-for="AuthorsSchool" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary mt-3">Update Author</button>
</form>